# Configuration file
#
# Note:
#   * - relative from project directory as root
#   **- relative from @experiment_dir as root
#
default:
  # Common ----
  experiment_version: '2021-02-22'
  experiment_dir: '.' # *
  data_dir: '../data' # **
  cache_dir: 'cache' # **
  output_dir: 'output' # **
  log_dir: 'logs'
  
  # Cerberus settings ----
  depth_in_minutes: 4320
  exchange_fee_pcnt: 0.03
  min_exchange_n: 2
  stable_coin_symbol: 'USDT'
  risks:
    min_order_volume_in_usdt: 0.10
    max_order_volume_in_usdt: 50.0
  connected_bot_status: 4
  pairs:
    stable_coin_list: ['TUSD', 'USDT', 'PAX']
    ignore_list: ['HOT/BTC', 'HOT/ETH']
  
  # Misc ----
  verbose: 1
